"""Blender execution services for InterDeCA."""

import os
import subprocess
import sys
import tempfile
from pathlib import Path

from color_deca.interdeca.core.blender_scripts import BlenderScriptFactory
from color_deca.interdeca.types import BlenderBakeParameters, BlenderUvParameters


class BlenderExecutableService:
    """Resolve Blender executables without UI dependencies."""

    def find(self, explicit: Path | None = None) -> Path | None:
        if explicit is not None:
            candidate = Path(explicit).expanduser()
            return candidate if candidate.is_file() else None

        env_path = os.environ.get("BLENDER_EXECUTABLE") or os.environ.get("BLENDER_PATH")
        if env_path:
            candidate = Path(env_path).expanduser()
            if candidate.is_file():
                return candidate

        if sys.platform == "darwin":
            candidates = [
                Path("/opt/homebrew/bin/blender"),
                Path("/Applications/Blender.app/Contents/MacOS/Blender"),
            ]
        else:
            candidates = [Path("/usr/bin/blender"), Path("/usr/local/bin/blender")]

        for candidate in candidates:
            if candidate.is_file():
                return candidate
        return None

    def require(self, explicit: Path | None = None) -> Path:
        blender = self.find(explicit)
        if blender is None:
            raise FileNotFoundError("Blender executable not found")
        return blender


class BlenderTextureBakeService:
    """Run Blender scripts generated by :class:`BlenderScriptFactory`."""

    def __init__(self, script_factory: BlenderScriptFactory | None = None):
        self.script_factory = script_factory or BlenderScriptFactory()

    def run_prepare_atlas(
        self,
        blender_executable: Path,
        in_obj: Path,
        out_obj: Path,
        parameters: BlenderUvParameters,
    ) -> None:
        script = self.script_factory.build_prepare_atlas_script()
        args = self.script_factory.prepare_atlas_args(in_obj, out_obj, parameters)
        self._run_script(blender_executable, script, args)

    def run_bake_texture(
        self,
        blender_executable: Path,
        source_mesh: Path,
        target_mesh: Path,
        input_texture: Path,
        output_texture: Path,
        parameters: BlenderBakeParameters,
    ) -> None:
        script = self.script_factory.build_bake_texture_script()
        args = self.script_factory.bake_texture_args(
            source_mesh,
            target_mesh,
            input_texture,
            output_texture,
            parameters,
        )
        self._run_script(blender_executable, script, args)

    def _run_script(self, blender_executable: Path, script_text: str, script_args: list[str]) -> None:
        blender = Path(blender_executable).expanduser()
        if not blender.is_file():
            raise FileNotFoundError(f"Blender executable not found: {blender}")

        with tempfile.NamedTemporaryFile("w", encoding="utf-8", suffix=".py", delete=False) as script_file:
            script_file.write(script_text)
            script_path = Path(script_file.name)

        command = [
            str(blender),
            "--background",
            "--factory-startup",
            "--python",
            str(script_path),
            "--",
            *script_args,
        ]
        subprocess.run(command, check=True)
